[package]
name        = "osmos-daemon"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "osmos-daemon"
path = "src/main.rs"

[dependencies]
osmos-core       = { path = "../osmos-core" }
osmos-transport  = { path = "../osmos-transport" }
tokio            = { workspace = true }
tokio-util       = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }
uuid             = { workspace = true }
thiserror        = { workspace = true }
anyhow           = { workspace = true }
tracing          = { workspace = true }
tracing-subscriber = { workspace = true }
dirs               = { workspace = true }
